name: okito
description: Your best coding friend. State management, navigation management,
  local storage, dependency injection, cool extensions with best usages and with
  the support of best utilities!
version: 1.0.8
homepage: https://github.com/ragokan/okito
repository: https://github.com/ragokan/okito

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
