name: okito
description: Okito is the simplest state management solution ever, at least I think so. If depends on nothing, works really fast with minimum code usage.
version: 1.0.0
homepage: https://github.com/ragokan/okito
repository: https://github.com/ragokan/okito
authors:
  - okanyldrmop@gmail.com

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.7
  flutter:
    sdk: flutter
