name: okito
description: Okito is the simplest state management solution ever, at least I
  think so. It depends on nothing, works really fast with minimum code usage.
version: 1.0.6
homepage: https://github.com/ragokan/okito
repository: https://github.com/ragokan/okito

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
