name: okito
description: Your best flutter coding friend. All in one flutter helper with state, route, navigation, localization, dependency injection and local storage management!
version: 1.2.5
homepage: https://github.com/ragokan/okito
repository: https://github.com/ragokan/okito

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
